/* set compiler variable gnat30  */
/* 'set c_include_path='    */
'@echo off'
'set c_include_path=d:\gnat30\include'              /* xxx.c xxx.h files  */
/* 'set ada_include_path='   */
'set ada_include_path=d:\gnat30\gnatads;d:\gnatadb' /* xxx.ads  files     */
'set ada_objects_path=d:\gnat30\gnatlib;'           /*xxx.obj  xxx.o xxx.ali   */
'set gcc_exec_prefix=d:\gnat30\bin'                 /* xxx.exe  files     */
'set library_path=d:\gnat30\lib'
'set emxopt=-c -n -K -E '
'set tmp=d:\temp'
'set lib='
'set lib=d:\gnat30\lib;d:\cpp\lib;c:\os2;'         /*  xxx.lib  files     */
